app/uk/gov/hmrc/apprenticeshiplevy/connectors/EDHConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/EPSModel.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/RTIConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/EmploymentCheckController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionsController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/LevyDeclarationController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/live/LiveEmprefController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/live/LiveFractionsController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/live/LiveLevyDeclarationController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/sandbox/SandboxEmprefController.scala
app/uk/gov/hmrc/apprenticeshiplevy/utils/DateRange.scala
conf/app.routes
conf/sandbox.routes
docs/Apprenticeship Levy Declarations API.md
docs/Fraction Calculations.md
public/api/definition.json
public/documentation/1.0/fraction-calculations.xml
public/documentation/1.0/levy-declarations.xml
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionsControllerSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/LevyDeclarationControllerSpec.scala

Needs the corresponding change on the stub to be merged at the same time.

Changed the parameters on `declarations` and `fractions`

---

ChangeLog.md
conf/application.conf

Added ChangeLog to document changes that may/will impact consumers of the API.

DDCNLS-128: Enabled httpOnly setting on session cookies to prevent misuse.

---

.travis.yml
it/uk/gov/hmrc/apprenticeshiplevy/IntegrationTestSuite.scala
it/uk/gov/hmrc/apprenticeshiplevy/util/WiremockNotifier.scala

Run integration tests regardless of system properties printing warnings.

DDCNLS-110: Updating travis config to run integration tests

---

app/uk/gov/hmrc/apprenticeshiplevy/connectors/EDHConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/ApiController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionsController.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/LevyDeclarations.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/des/Faction.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/des/FractionCalculation.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/des/Fractions.scala
it/resources/mappings/123AB12345/fractions_200.json
it/resources/mappings/123AB12345/fractions_200_closed_date.json
it/resources/mappings/123AB12345/fractions_200_open_date.json
it/resources/mappings/123AB12345/fractions_200_range_date.json
it/resources/mappings/errors/fractions_400.json
it/resources/mappings/errors/fractions_401.json
it/resources/mappings/errors/fractions_403.json
it/resources/mappings/errors/fractions_404.json
it/resources/mappings/errors/fractions_500.json
it/resources/mappings/errors/fractions_503.json
it/uk/gov/hmrc/apprenticeshiplevy/FractionsEndpointISpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/EDHConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FactionCalculationControllerSpec.scala

Added unit tests for fractions endpoint and EDH connector.

DDCNLS-332: Updating fractions endpoint tests to return new json according to DES specs.

---

app/uk/gov/hmrc/apprenticeshiplevy/controllers/EmploymentCheckController.scala
it/resources/mappings/errors/employment_check.json
it/resources/mappings/errors/employment_check_400.json
it/resources/mappings/errors/employment_check_400a.json
it/resources/mappings/errors/employment_check_401.json
it/resources/mappings/errors/employment_check_403.json
it/resources/mappings/errors/employment_check_404.json
it/resources/mappings/errors/employment_check_404a.json
it/resources/mappings/errors/employment_check_404c.json
it/resources/mappings/errors/employment_check_404d.json
it/resources/mappings/errors/employment_check_500.json
it/resources/mappings/errors/employment_check_503.json
it/uk/gov/hmrc/apprenticeshiplevy/EmploymentCheckEndpointISpec.scala

Updated associated tests and wiremock mappings.

DDCNLS-367: Enabled des error handler on employment check endpoint.

---

app/uk/gov/hmrc/apprenticeshiplevy/connectors/Audit.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/audit/ALAEvent.scala
conf/application.conf
project/MicroServiceBuild.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FactionCalculationControllerSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionCalculationDateControllerSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/LevyDeclarationControllerSpec.scala

Turned off implicit auditing for sandbox connectors/controllers.

DDCNLS-333: Added explicit auditing for des and auth connectors.

---

app/uk/gov/hmrc/apprenticeshiplevy/audit/Audit.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/audit/ALAEvent.scala
app/uk/gov/hmrc/apprenticeshiplevy/metrics/Metrics.scala
app/uk/gov/hmrc/apprenticeshiplevy/metrics/Timer.scala
conf/application.conf
it/uk/gov/hmrc/apprenticeshiplevy/config/IntegrationTestConfig.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnectorSpec.scala

DDCNLS-330: Implemented external metrics for DES timings.

---

app/uk/gov/hmrc/apprenticeshiplevy/config/AppContext.scala
conf/application.conf
docs/endpoints/xml/04_employment-check.xml
docs/endpoints/xml/xsl/doc-v2-raml.xslt
it/resources/data/expected/employment-check.xml
public/api/conf/1.0/application.raml
public/api/conf/1.0/examples/get-employment-status.json
public/documentation/1.0/employment-check.xml

DDCNLS-142: Adding optional path to DES to allow to point to sandbox in QA.

---

app/uk/gov/hmrc/apprenticeshiplevy/config/AppContext.scala
app/uk/gov/hmrc/apprenticeshiplevy/metrics/Metrics.scala
conf/logback.xml

DDCNLS-142: Configuring logging

---

conf/application.conf
conf/logback.xml
it/uk/gov/hmrc/apprenticeshiplevy/IntegrationTestSuite.scala

Configured logging levels for connector.

DDCNLS-470: Added configuration for privileged access.

---

app/uk/gov/hmrc/apprenticeshiplevy/audit/Audit.scala
app/uk/gov/hmrc/apprenticeshiplevy/config/AppContext.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/ApiController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionsController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/live/LiveFractionsController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/sandbox/SandboxFractionsController.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/audit/ALAEvent.scala
conf/app.routes
conf/application.conf
it/uk/gov/hmrc/apprenticeshiplevy/config/IntegrationTestConfig.scala
public/sandbox-data/apprenticeship-levy/employers/840MODES17/designatory-details.json
public/sandbox-data/apprenticeship-levy/employers/840MODES17/employed/AA123456C.json
public/sandbox-data/apprenticeship-levy/employers/840MODES17/employed/SC111111A.json
public/sandbox-data/apprenticeship-levy/employers/840MODES17/fractions.json
public/sandbox-data/epaye/840/MODES17/designatory-details.json
public/sandbox-data/rti/employers/840MODES17/employer-payment-summary.json
test/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FactionCalculationControllerSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionCalculationDateControllerSpec.scala

Added configuration for DES environment and token

DDCNLS-334: Updating audit event details

---

app/uk/gov/hmrc/apprenticeshiplevy/audit/Audit.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/ApiController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/ErrorResponses.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/audit/ALAEvent.scala
it/uk/gov/hmrc/apprenticeshiplevy/DeclarationsEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/EmploymentCheckEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/EmploymentRefEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/FractionsCalculationDateEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/FractionsEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/RootEndpointISpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/AuthConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnectorSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/FractionCalculationDateControllerSpec.scala

DDCNLS-334: Updated audit events to have upstream http status.

---

app/uk/gov/hmrc/apprenticeshiplevy/controllers/RootController.scala
conf/logback.xml
it/uk/gov/hmrc/apprenticeshiplevy/RootEndpointISpec.scala

Updated logging configuration.

DDCNLS-334: Disable root endpoint when privileged access

---

app/uk/gov/hmrc/apprenticeshiplevy/controllers/sandbox/data/TestDataController.scala
it/uk/gov/hmrc/apprenticeshiplevy/DeclarationsEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/DefinitionEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/DocumentationEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/EmploymentCheckEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/EmploymentRefEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/FractionsCalculationDateEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/FractionsEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/TestDataEndpointISpec.scala
it/uk/gov/hmrc/apprenticeshiplevy/config/IntegrationTestConfig.scala

DDCNLS-488: Added filtering by date ranges for sandbox test data

---

app/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnector.scala
docs/endpoints/xml/05_fraction-calculations.xml
docs/endpoints/xml/xsl/doc-v2-raml.xslt
docs/get-employer-fraction-calculations.bak.md
it/resources/data/expected/fraction-calculations.xml
it/resources/mappings/864TZ00000/fractions_200.json
it/uk/gov/hmrc/apprenticeshiplevy/FractionsEndpointISpec.scala
public/api/conf/1.0/application.raml
public/documentation/1.0/fraction-calculations.xml

Updated api documentation.
Fixed raml generation to produce endpoint documentation in filename order.

DDCNLS-210: Fixing regex for fraction calculation data

---

app/uk/gov/hmrc/apprenticeshiplevy/audit/Audit.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/DesController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/LevyDeclarationController.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/RootController.scala
app/uk/gov/hmrc/apprenticeshiplevy/metrics/Metrics.scala
app/uk/gov/hmrc/apprenticeshiplevy/metrics/Timer.scala
docs/endpoints/xml/03_levy-declarations.xml
docs/get-employer-levy-declarations.bak.md
public/api/conf/1.0/application.raml
public/documentation/1.0/levy-declarations.xml

Update to documentation.
Tweaking logging to prevent large number of exceptions for BAU events.

DDCNLS-727: Re-enable metrics

---

ac/resources/local/live/fraction/754NZ00046-1.json
ac/resources/local/live/fraction/754TZ00047-1.json
ac/resources/local/live/levy/123AB12345-1.json
ac/resources/local/sandbox/fraction/754NZ00046-1.json
ac/resources/local/sandbox/fraction/754TZ00047-1.json
ac/resources/local/sandbox/levy/123AB12345-1.json
app/uk/gov/hmrc/apprenticeshiplevy/data/api/LevyDeclarations.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/des/EmployerPaymentSummary.scala
docs/endpoints/xml/03_levy-declarations.xml
docs/get-employer-levy-declarations.bak.md
it/uk/gov/hmrc/apprenticeshiplevy/DeclarationsEndpointISpec.scala
public/documentation/1.0/levy-declarations.xml
test/uk/gov/hmrc/apprenticeshiplevy/data/api/LevyDeclarationSpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/data/des/EmployerPaymentSummarySpec.scala

Updated documentation for levies endpoint.

DDCNLS-851: Updated levies objects ids to be unique rather than submission id.

---

app/uk/gov/hmrc/apprenticeshiplevy/controllers/sandbox/data/TestDataController.scala
it/uk/gov/hmrc/apprenticeshiplevy/TestDataEndpointISpec.scala
public/api/conf/1.0/application.raml
public/api/conf/1.0/sandbox/get-employer-details.md
public/api/conf/1.0/sandbox/get-employer-fraction-calculations.md
public/api/conf/1.0/sandbox/get-employer-levy-declarations.md
public/api/conf/1.0/sandbox/get-employment-status.md

Updated test data documentation.

DDCNLS-954: Added support for static test data in new external test environment.

---

app/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnector.scala
app/uk/gov/hmrc/apprenticeshiplevy/controllers/DesController.scala
app/uk/gov/hmrc/apprenticeshiplevy/data/des/EmployerPaymentSummary.scala
docs/endpoints/xml/03_levy-declarations.xml
docs/get-employer-levy-declarations.bak.md
it/resources/mappings/errors/declarations_des_oddity1.json
it/resources/mappings/errors/declarations_des_oddity2.json
it/resources/mappings/errors/declarations_des_oddity3.json
it/resources/mappings/errors/declarations_des_oddity4.json
it/uk/gov/hmrc/apprenticeshiplevy/DeclarationsEndpointISpec.scala
public/api/conf/1.0/application.raml
public/documentation/1.0/levy-declarations.xml
test/uk/gov/hmrc/apprenticeshiplevy/connectors/DesConnectorSpec.scala

DDCNLS-1070: Fix for DES returning json not adhering to specification.

---

app/uk/gov/hmrc/apprenticeshiplevy/metrics/Timer.scala

Doesn't time successful calls or log 404 as separate metrics.

DDCNLS-1228: Reducing metrics creation further.

---

project/build.properties

DDCNLS-1442: upgraded sbt version

DDCNLS-1442: upgraded sbt version

---

public/api/conf/1.0/application.raml

Corrected formatting for RAML

---

app/uk/gov/hmrc/apprenticeshiplevy/controllers/auth/AuthAction.scala
it/uk/gov/hmrc/apprenticeshiplevy/EmploymentRefEndpointISpec.scala
test/uk/gov/hmrc/apprenticeshiplevy/controllers/auth/AuthActionSpec.scala

Backed out PR 174
